name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: tests
        run: |
          python3 -m pip install --upgrade pytest pytest-cov
          python3 -m pip install -e .
          python3 -m pytest
      - name: build
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
